name = "smart-elderly-care"
compatibility_date = "2025-12-30"

# Cloudflare Pages 构建输出目录
pages_build_output_dir = "dist"

# D1 数据库绑定
# 本地开发时会自动在 .wrangler/state 目录创建本地数据库
[[d1_databases]]
binding = "DB"
database_name = "smart-elderly-care-db"
database_id = "b76d76d2-6728-4231-834d-09e1652a5a41"

# KV 存储绑定
# 本地开发时会自动在 .wrangler/state 目录创建本地 KV
[[kv_namespaces]]
binding = "KV"
id = "f7d3aa801b0142f88c377b6ca3e796e6"
